# Generated by Django 4.0.4 on 2022-04-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
